name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Instalar dependencias
        run: npm install

      - name: Verificar instalación
        run: ls -la node_modules

      - name: Verificar jest instalado
        run: ls -la node_modules/.bin/

      - name: Ejecutar pruebas con npx
        run: npx jest

      - name: Ejecutar pruebas con npm test (si npx no funciona)
        run: npm test
