name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Verificar versión de Node.js
        run: node -v

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Instalar dependencias con npm ci
        run: npm ci

      - name: Verificar node_modules
        run: ls -la node_modules

      - name: Verificar jest en node_modules/.bin/
        run: ls -la node_modules/.bin/

      - name: Ejecutar pruebas con npx
        run: npx jest
